<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
    <PackageReference Include="Wasmtime" Version="34.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\src\legacy\ett\versions\minaclac-72.3.wasm">
      <Link>Assets\minaclac-72.3.wasm</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\src\legacy\ett\versions\minaclac-74.0.wasm">
      <Link>Assets\minaclac-74.0.wasm</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\src\legacy\estimator\companella\dan_model.onnx">
      <Link>Assets\dan_model.onnx</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\src\legacy\estimator\intervals.js">
      <Link>Assets\intervals.js</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
