<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>osu.Game.Rulesets.ManiaMapAnalyser</AssemblyTitle>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>osu.Game.Rulesets.ManiaMapAnalyser</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\osu\osu.Game\osu.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\intervals.js">
      <LogicalName>OsuManiaMapAnalyser.Core.Assets.intervals.js</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
